spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/cdatabase?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
#配置xml路径
mybatis:
  mapper-locations: classpath:Mybatis/mapper/*.xml

debug: true

#logging:
#  level:
#    com.lhpang.ac.dao : debug

#mybatis显示sql语句的配置
logging:
  level:
    com.lhpang.ac.dao : trace
