#支付宝配置
alipay:
  # 支付宝网关名
  open_api_domain : https://openapi.alipaydev.com/gateway.do
  mcloud_api_domain : http://mcloudmonitor.com/gateway.do
  #商户UID
  pid : 2088102177876458
  #APPID
  appid : 2016092900627573
  #商户私钥
  private_key : MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCkS13Q1ICjCtJAnzLV/3wwiDFfWsiSoOoOResa7b5rFukwgIPMrg85MOsiS9Lj/2jjFnPEg4gcp1jOXuGZZRGHQYXx53GNCI3FlRizM9JYsvzAjHj3gzCWCDYKOqSVgx4BTnrotsQ/zs6OM081TG5FEux+8HakDyayliRoQ0TEMQ5KYih+2LS295erDR47lnygHDUnjIipKN2t3RDCVoMv6Rc2qYDewznsi71FVHOvjmFBBtAFQVDfPkBf7ATp33KzT3WeWrTfTddEwXo58QSPW0qPbIzACft+Y2ibjjn4EZM67fiKmDnIUpxJmm+s5c+8yGDDbRgLi3sUilMQlWkxAgMBAAECggEADWY8K4j5SNLcHPse6Uch+M9Sv4Um8JaBIFLhftu++PrwX81LcokLos1zj+OBOqkdA9BT9sYHdtbLLmGcoqcUi+RzKSyIHUmCTof/cLYcRLGsXYPXZdBkSQg4aBMqUytTaiXdbldhoBac0AotPpqSL74AXcX81xqJPG10YLCDzkBUALXX0TiJOUrnVvnb9sP6s/DbijUYriAQSrlbBTYKjTk3SB5vgz53E0a9iFU4cA6bW7FFpPoolpE4niZwhbOJlKjwa3YK1eT9Q7qrD0ljnRPbkx21VxWN71d5r4hY2p6Cj7jwdPz2k75V8yiuJWX13YraywBwu+5zWM0CLf4sQQKBgQD0yqiIPCoGUZKhmXWM33OXL2DWPsIMDKvWlT//KcoZbfvTns75hdNr8wNrzYR72cn2uZ4tHh/wasxgGJvgcc3a+5v/INPzfaALdjMIE68GfRGyYrGSXLR9yY3xN19gGCVqWPtMfUN1UWlreXISJaj7dUPGEie+wTpntc/9ctJiGQKBgQCr0SeFMlVJlbbtdA4cg3YFGlmX8w7WsQw259+C/BJjLuZLhxqVD4/zcPGyZ4oyHDgQLyfRZa3Tj2tB95CTxVIkVBoZOBqkQ6gvTHnosTpuBzN7xixTAQ7YO7wtJ0I66Xvuugb4l5Wjbks/NLUdZI5uGEJA2Q+G9uwZZI3XOH6S2QKBgQC7xjlBR+V0s14nV/Az/7RLZKyDq+BuHcoy8IoG0aeVmihyTH+4KE/lnqQhLaVS291wxTHwqgsWANaFYFsx8BpYwGkJa8UqIlOCd0juCStZbtcEX3CXNUW+t72KK0+eBuesjFU4d14nwCt9pcs64Gife3Rhm8uhJ9gFdhH1+P4pAQKBgAPwvQZJ/Di+zT4u3i/7N9awHwPkGCAGWXBc6vxXCZjqt29d/tcST0vW+EQOKdYyXXrJihE8Urs6W8xcgB1TdinNH/gaGEpSHuZOy7Dxd5SUZ7Lb/aI9sPh2jj8+2j79odD8xTIoT886tVESxWCSMM4HkmVoVPnUad+/NZ2M9yIpAoGBALtuKL6uFJXlLCsKkN97rsyXsJOtpP26RDiRDEE1lSavZtNiIIihSYFyApbNToXerX1Wvtg415jR3b0hZQvJWDT8DdhXeKyDtlo4KtIzJAchtvsiw7G78khvN0Z/noHdMrM7NtLgdqPSZx3L5LFk1YKJaO5RB4/B0kUhqIOp2HbO
  #商户公钥
  public_key : MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApEtd0NSAowrSQJ8y1f98MIgxX1rIkqDqDkXrGu2+axbpMICDzK4POTDrIkvS4/9o4xZzxIOIHKdYzl7hmWURh0GF8edxjQiNxZUYszPSWLL8wIx494Mwlgg2CjqklYMeAU566LbEP87OjjNPNUxuRRLsfvB2pA8mspYkaENExDEOSmIofti0tveXqw0eO5Z8oBw1J4yIqSjdrd0QwlaDL+kXNqmA3sM57Iu9RVRzr45hQQbQBUFQ3z5AX+wE6d9ys091nlq0303XRMF6OfEEj1tKj2yMwAn7fmNom445+BGTOu34ipg5yFKcSZpvrOXPvMhgw20YC4t7FIpTEJVpMQIDAQAB
  #支付宝公钥
  alipay_public_key : MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn57mPTgS56vo3HFNDu6vgeGef5Iz2aba3uSnV8JYyGvb3z83onmX+DkQ/KZ/KD1LD04C/81roA0nw0jYUdWcu5tZo28yI+ewzxea1kuTZCoaUXqEAIfIUlCvz6yFMwVYJFS7ddhBz5eKucjePtmioBbEgn2URuCiEPkWzHgoMgEAcgegmKo7ax69oV7HLVTXRyK8/k/0pF91OkDs4In3E0fAb1z0EksO7ZKxt3zxyLd9aq81L0a2AbRO/3awWUxwY6WaqmGk3AMuCkHs7Ue0sbqvtKy1rGKn3EJnFAQ3N+xtJIGOF3ZD3feYqIs1UMzxvYfp3EyLTCHvk8DRHXMxBwIDAQAB
  # 签名类型: RSA->SHA1withRsa,RSA2->SHA256withRsa
  sign_type : RSA2
  # 当面付最大查询次数和查询间隔（毫秒）
  max_query_retry : 5
  query_duration : 5000
  # 当面付最大撤销次数和撤销间隔（毫秒）
  max_cancel_retry : 3
  cancel_duration : 2000
  # 交易保障线程第一次调度延迟和调度间隔（秒）
  heartbeat_delay : 5
  heartbeat_duration : 900
  # 回调地址
  notify-url : http://pph.nat300.top/order/aliPayCallback



#数据源配置
spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/cdatabase?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/

#配置MyBatis xml路径
mybatis:
  mapper-locations: classpath:Mybatis/mapper/*.xml

#logging:
#  level:
#    com.lhpang.ac.dao : debug

#mybatis显示sql语句的配置
logging:
  level:
    com.lhpang.ac.dao : trace

